// <auto-generated />
namespace teqBlog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207080330577_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozb/RU/K6mIsLT9Kj8siIyxe5+X5e6K08xAofWQ7o+5OCa32+s31KucuP/sIXb2smtZvRe1+r/w6+IA+ellXq7xur1/l5513z55+lN4N37/bBWBfj7wLdD776GzZ3tv7KH2xLstsUtIH51nZ5B+lq08fvW6rOv88X+Z11uazl1nb5jVN0tks5+EoWR6tPr0dZR7e3dkDZe5my2XVZi3NeG8AHXTfFG2ZG0xftzVxz0fps+JdPnueLy/aucX2i+yd+WR/Z4eY6KtlQdyGea3XuT88+Xtzt0+q2fUPodcX2WVxwXTo9P9yXrUV8eCrvOSvm3mxElYc81e/v2Wf9FldLV5VpXnJfvP7v8nqi5wavKmiX7+u1vW0g9Lju45PN3Ivw/o6rMsvfh2+tS/+f4BpnxVljt9+CBz0taX7tpzoGO1DeNEw2wAvGla9DS8eN001LRgTnzUcFuHATpezdDNKMkV2ODQl67ItVmUxpd4/++hbPVoNgrQS50A62oRQd0M0CeqXy6d5mbd5ejxt2RSeZM00m/WniugyCz8h8cprcHdWksFr2jorlm1fFovltFhl5UbcO2+9p/kBdraf7jdP81W+hBBunI8PR8D20yHbTVR6fNdjrb72o3daeiOvFQl1F/jLIm96bId3XudtB2XS6Y6tezzSY7QQiPJnD4B+3nnbG00HhCexXqO4THfJe6M8WaQtvr0pulGAPBge4bpyEA4wojrslNnvHt8Vv08/eHx3wEF8/EW2WpHO9hxG/SR9Ld7iyfbr9/cKFwLj7jRgly6D2Z7IkGUXeedb6powfVbUTfs0a7NJBm1+Mlv0mt2SQU1vXT7tT5rhOvMGfg9kQV1nx9B9YdZ3n9HAFlAFbKwj091/NYXPnpVZvcHknVTlerG8WUkMQ1N/0wekH90ehjiPAS78SR/C47sdevSUWY/qPVsQTuOtJjnivb3fBEcB3GJ2B94bIqT1+XxaDniQm+A4f8wH5D69PaSvx2w/q9PcU3bdJrZ3q/Q6yu2xKppAA6axELmneaTJRymR6bKYQeu8vm7afDFGg/HrX1S+zmvKAZzk430E9qbZF9myOM+b9k31Nie7w9993XDb+udNMyv/vxJzk+fxUXpjoHKT074pVl5eZvV0ntWRCOM9QwovFP6aQP+/E1b+rMxLNxz8mlS8NV9tRO8bD6ucL/nDDns6buTXCeW+VuS0wb15H72BMb1fsPQNdGjhdoj7DQdHfRe1O3Xx8GhjdCTG5rOPZhPMtXD4cHjQ7eKG4CkGnL/qQ/7ZDqy6xAgd4xvDqZtDsG8mdOp7DcRGa3p7IYqFeLgpLhwIJOOX+TRgINvmbHleGV7uYGSadJTfF3mbzYi7juu2OM+mLX09zZuGE20/mZVranK6mOSzs+WX63a1bmnI+WJSBn445GFT/xwfhjg//nLFSbBvYgiEZkFDyL9cPlkX5czi/SyitgdAQNDUVGEuW5isi2sL6UW1vCUgJd9Tox/e5IsV5fvy5svl6+wyH8btZhqGFHv8tMgu6mzhU1A+UUxeZ9Sz1wV14L/h+qM/iV1p7efo/wkAAP//hUsiTHAaAAA="; }
        }
    }
}
